#!/bin/bash

paste <(bash /etc/update-motd.d/scripts/hostname && bash /etc/update-motd.d/scripts/sysinfo && bash /etc/update-motd.d/scripts/services) <(bash /etc/update-motd.d/scripts/diskspace && bash /etc/update-motd.d/scripts/docker) | column -s $'\t' -tne

echo ""
