#!/bin/bash

# Use script location as root for relative paths
parent_path=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )
cd "$parent_path"

paste <(./scripts/hostname && ./scripts/sysinfo && ./scripts/services) <(./scripts/diskspace && ./scripts/pm2) | column -s $'\t' -tne

echo ""
