#!/bin/bash

# set column width
COLUMNS=2
# colors
cyan="\e[36m"
green="\e[32m"
red="\e[31m"
white="\e[0m"

mapfile -t containers < <(docker ps -a --format '{{.Names}}\t{{.Status}}' | awk '{ print $1,$2 }')

out=""
for i in "${!containers[@]}"; do
    IFS=" " read name status <<< ${containers[i]}
    # color green if service is active, else red
    if [[ "${status}" == "Up" ]]; then
        out+="${green}●${white} ${name}${undim},"
    else
        out+="${green}▲${white} ${name}${undim},"
    fi
    # insert \n every $COLUMNS column
    if [ $((($i+1) % $COLUMNS)) -eq 0 ]; then
        out+="\n"
    fi
done
out+="\n"

printf "\n${cyan}Docker status${white}\n"
printf "$out" | column -ts $',' | sed -e 's/^/  /'
