#!/bin/bash

color="\e[36m"
reset="\e[0m"

hostname=$(hostname)
#echo -e "${color}$(figlet -f slant $hostname)${reset}"

figlet -f slant $hostname | \
while IFS= read -r ; do
    echo -e "${color}$REPLY ${reset}"
done
