#!/bin/bash
export LANG='en_US.UTF-8'

color_primary="\e[36m" #cyan
color_danger="\e[31m" # Red
color_warning="\e[33m" # Yellow
color_success="\e[32m" # Green
color_reset="\e[0m"

# Declare array of services and pretty human readable names
declare -a services=(
"docker"
"ufw"
"fail2ban"
)
declare -a serviceName=(
"Docker"
"UFW"
"Fail2Ban"
)
declare -a serviceStatus=()

# Get status of all my services
for service in "${services[@]}"
do
    serviceStatus+=($(systemctl is-active "$service.service"))
done

# Maximum column width
#width=$((49-2))
width=$((34))

# Current line and line length
line=""
lineLen=0

echo -e "\n${color_primary}Services running${color_reset}"

for i in ${!serviceStatus[@]}
do
    # Next line and next line length
    next="  ${serviceName[$i]}"
    nextLen=$((1+${#next}))

    # If the current line will exceed the max column with then echo the current line and start a new line
    if [[ $((lineLen+nextLen)) -gt width ]]; then
    echo -e "$line"
    lineLen=0
    line=""
    fi

    lineLen=$((lineLen+nextLen))

    # Color the next line green if it's active, else red
    if [[ "${serviceStatus[$i]}" == "active" ]]; then
    line+="${color_success}●${color_reset} ${serviceName[$i]} "
    else
    line+="${color_warning}▲${color_reset} ${serviceName[$i]} "
    fi
done

# echo what is left
echo -e "$line"

