#!/bin/bash

echo ""
cat /etc/*release | grep "PRETTY_NAME" | cut -d "=" -f 2- | sed 's/"//g'
uname -sr
uptime=$(uptime | sed -E 's/^[^,]*up *//; s/, *[[:digit:]]* users.*//; s/ days/d/; s/ min/m/; s/([[:digit:]]+):0?([[:digit:]]+)/\1h, \2m/')
echo "Up $uptime"
